#! /bin/sh

set -e

case "$1" in
  configure|upgrade)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
      # FIXME: only force session on initial install, use --keep-old on 
      # upgrades?
      /usr/lib/lightdm/lightdm-set-defaults --session=freegeek || true
      /usr/lib/lightdm/lightdm-set-defaults --greeter=lightdm-gtk-greeter || true
    fi
    ;;
esac

if [ "$1" = "configure" ] ; then
  update-alternatives --install /etc/lightdm/lightdm-gtk-greeter.conf \
    lightdm-gtk-greeter-config-derivative \
    /etc/xdg/xdg-freegeek/lightdm/lightdm-gtk-greeter.conf 90
fi

case "$1" in
  configure|upgrade)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --session=freegeek || true
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --greeter=lightdm-gtk-greeter || true
    fi
  ;;
esac

#DEBHELPER#
